### ISSUE TITLE
dudin-file-text-reader

### ISSUE THREAD

**Issue by cvelele** [dudintv/vizartist-scripts#2]
I am sorry if boring you. 
Is this script like typewriting text?
Code is OK, but cant apply. When click Read the file nothing happens?

![script2](https://user-images.githubusercontent.com/19627658/189680771-cced355c-b6e0-497a-be44-f63aa9688a54.PNG)

![script3](https://user-images.githubusercontent.com/19627658/189681063-74361b6f-2b09-4e21-9615-58907286d723.PNG)

![script1](https://user-images.githubusercontent.com/19627658/189680816-ad19f5a7-b1bb-4083-b4f0-1dc908f875ac.PNG)

**Comment by dudintv** [comment]
@cvelele thank you for the feedback!

Probably you expect this text directly into your text geometry. But this script put the data into a global variable in System SharedMemory.

In your case, you've written "Open-Sans-Bold" in the "variable name" field but it's just the container name. 

I can upgrade the script in order to put the text directly in a text geometry... It will take some time ;)

**Comment by cvelele** [comment]
Sorry, I am relatively new with script in Vizartist. Sometimes don't know how to apply.
Is this script like typewriting text?

If you have time ok, if not that is ok too.
Thx

**Comment by dudintv** [comment]
Check this out:
https://github.com/dudintv/vizartist-scripts/tree/master/dudin-file/dudin-file-text-reader
I've upgrade the script. Now you can choose where the text will be appeared. The new way is "Text geometry". If you don't select this container (it's ok) it means that the target container with "text geometry" is the current "this" container where the script is laying.

It's definitely not the "typewriting text" effect. If you need it — please use standard "TextFX Alpha" plugin.

**Comment by dudintv** [comment]
For example:

![2022-09-13_20-36-17](https://user-images.githubusercontent.com/951452/189983439-6dbfe77f-0b84-4965-a175-b8a01991d93f.png)

If you put some another container in this placeholder — the output will be printed out to the selected container.

**Comment by cvelele** [comment]
Awesome. 
Now I get it. This reading interval is for refreshing / reading new data from txt file, like updating.

Didn't go through all your script so this is the question.
Is there a script like this (text-reader) but instead of txt (i give him a path to file) and it will put picture or icon on container?

Sorry for asking too much, but ideas just keep coming.

**Comment by dudintv** [comment]
This a good idea how to rename the parameter to "Auto-update interval" :)

About the pictures. There is the dedicated standard build-in plugin for that. It's "Image Control". In Trio or Pilot, you can specify the image. It can be either from your local/network drive or from Graphic Hub, etc...

**Comment by cvelele** [comment]
Yes I know for Image Control option. In that way operator in Trio or Pilot manually change picture.
But my idea is just like text-reader. Somewhere on disk drive are, for example, 3 images. Image01.jpg, image02.jpg and image03.jpg. Operator then can save different pictures under that same name (image01, image02, image03) from photoshop, and in that way scene will update to current picture.  

![script4](https://user-images.githubusercontent.com/19627658/190380019-fefbc903-aeea-49bc-bc32-f3c7c9bcb0dc.png)

**Comment by dudintv** [comment]
@cvelele hm, I still don't see the logic what you want to achieve... You can create a new picture in Photoshop, put it to the GH, open Trio/Pilot, select the new picture and take it in. This way is more appropriate (optimised) because it goes standard way.

If you want to load picture (somehow) by script even from local drive — you will get dropframes/freezes. In order to avoid that you will have to significantly increase buffer loop on your VizArtist. That leads to decline of responsiveness — the time delay between user action and real changings. If you can avoid this I would highly recommend to avoid.

**Comment by dudintv** [comment]
@cvelele anyway, can you describe more details of your logic what you want to have? How the script should understand that this picture is the current?

**Comment by cvelele** [comment]
Because it will always have the same name, and I will overwrite with different picture from photoshop.

**Comment by dudintv** [comment]
@cvelele this is an unstable thing. Then the file has the same name — vizrt consider it as not changed. And if VizEngine already loaded a picture it became cached. If you need to refresh it we need to remove the image from the cache it and reload again. And, we have to do this always, even when the image is not changed... Because there is no way to know that the image file was updated.

**Comment by cvelele** [comment]
OK. Understand.
Thanks for explanation.
